/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthRecoverRouteImport } from './routes/auth.recover'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAgendamentosRouteImport } from './routes/app.agendamentos'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendamentosRoute = AppAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AppRoute,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/agendar/$slug'
    | '/app/agendamentos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/onboarding'
    | '/auth/login'
    | '/auth/recover'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/agendar/$slug'
    | '/app/agendamentos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/onboarding'
    | '/auth/login'
    | '/auth/recover'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/agendar/$slug'
    | '/app/agendamentos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/onboarding'
    | '/auth/login'
    | '/auth/recover'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recover': {
      id: '/auth/recover'
      path: '/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendamentos': {
      id: '/app/agendamentos'
      path: '/agendamentos'
      fullPath: '/app/agendamentos'
      preLoaderRoute: typeof AppAgendamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendamentosRoute: typeof AppAgendamentosRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendamentosRoute: AppAgendamentosRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AgendarSlugRoute: AgendarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
